// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MroPlan.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MroPlan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514211309_NormalizasyonDuzeltmesi")]
    partial class NormalizasyonDuzeltmesi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MroPlan.Models.BakimGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtolyeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BakimGruplari");
                });

            modelBuilder.Entity("MroPlan.Models.BakimKontrolKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtananPersonelId")
                        .HasColumnType("integer");

                    b.Property<int>("BakimPlaniId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParcaSablonuId")
                        .HasColumnType("integer");

                    b.Property<string>("TeknisyenNotu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtananPersonelId");

                    b.HasIndex("BakimPlaniId");

                    b.HasIndex("ParcaSablonuId");

                    b.ToTable("BakimKontrolKayitlari");
                });

            modelBuilder.Entity("MroPlan.Models.BakimPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GeldigiBirlik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenelDurum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeliTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KabulTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BakimPlani");
                });

            modelBuilder.Entity("MroPlan.Models.ParcaSablonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BakimGrubuId")
                        .HasColumnType("integer");

                    b.Property<string>("HeliTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IslemSure")
                        .HasColumnType("integer");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParcaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParcaPN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BakimGrubuId");

                    b.ToTable("ParcaSablonlari");
                });

            modelBuilder.Entity("MroPlan.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtolyeKodu")
                        .HasColumnType("text");

                    b.Property<int?>("BakimGrubuId")
                        .HasColumnType("integer");

                    b.Property<string>("CalistigiYer")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IzinBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IzinBitis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BakimGrubuId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("MroPlan.Models.PersonelHareketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("HareketTipi")
                        .HasColumnType("text");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelHareketleri");
                });

            modelBuilder.Entity("MroPlan.Models.Yetkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("ParcaPN")
                        .HasColumnType("text");

                    b.Property<int>("ParcaSablonuId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YetkinlikSeviyesi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcaSablonuId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SicilNo", "ParcaPN")
                        .IsUnique();

                    b.ToTable("Yetkinlikler");
                });

            modelBuilder.Entity("MroPlan.Models.BakimKontrolKaydi", b =>
                {
                    b.HasOne("MroPlan.Models.Personel", "AtananPersonel")
                        .WithMany()
                        .HasForeignKey("AtananPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MroPlan.Models.BakimPlani", "BakimPlani")
                        .WithMany("KontrolKayitlari")
                        .HasForeignKey("BakimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MroPlan.Models.ParcaSablonu", "ParcaSablonu")
                        .WithMany()
                        .HasForeignKey("ParcaSablonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtananPersonel");

                    b.Navigation("BakimPlani");

                    b.Navigation("ParcaSablonu");
                });

            modelBuilder.Entity("MroPlan.Models.ParcaSablonu", b =>
                {
                    b.HasOne("MroPlan.Models.BakimGrubu", "BakimGrubu")
                        .WithMany()
                        .HasForeignKey("BakimGrubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimGrubu");
                });

            modelBuilder.Entity("MroPlan.Models.Personel", b =>
                {
                    b.HasOne("MroPlan.Models.BakimGrubu", "BakimGrubu")
                        .WithMany()
                        .HasForeignKey("BakimGrubuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BakimGrubu");
                });

            modelBuilder.Entity("MroPlan.Models.PersonelHareketi", b =>
                {
                    b.HasOne("MroPlan.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("MroPlan.Models.Yetkinlik", b =>
                {
                    b.HasOne("MroPlan.Models.ParcaSablonu", "ParcaSablonu")
                        .WithMany()
                        .HasForeignKey("ParcaSablonuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MroPlan.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcaSablonu");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("MroPlan.Models.BakimPlani", b =>
                {
                    b.Navigation("KontrolKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
