using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MroPlan.Migrations
{
    /// <inheritdoc />
    public partial class NormalizasyonDuzeltmesi : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ============================================================
            // BÖLÜM 1: Mevcut tablolar — IF NOT EXISTS ile güvenli oluştur
            // ============================================================
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BakimGruplari" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "AtolyeKodu" text NOT NULL,
                    "GrupAdi" text NOT NULL
                );

                CREATE TABLE IF NOT EXISTS "BakimPlani" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SeriNo" text NOT NULL,
                    "HeliTipi" text NOT NULL,
                    "GeldigiBirlik" text NOT NULL,
                    "KabulTarihi" timestamp with time zone NOT NULL,
                    "GenelDurum" text NOT NULL
                );

                CREATE TABLE IF NOT EXISTS "ParcaSablonlari" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "HeliTipi" text NOT NULL,
                    "ParcaAdi" text NOT NULL,
                    "ParcaPN" text NOT NULL,
                    "IslemTuru" text NOT NULL,
                    "IslemSure" integer NOT NULL,
                    "BakimGrubuId" integer NOT NULL,
                    CONSTRAINT "FK_ParcaSablonlari_BakimGruplari_BakimGrubuId"
                        FOREIGN KEY ("BakimGrubuId") REFERENCES "BakimGruplari" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "Personeller" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SicilNo" text NOT NULL,
                    "Ad" text NOT NULL,
                    "Soyad" text NOT NULL,
                    "AtolyeKodu" text,
                    "CalistigiYer" text,
                    "Unvan" text,
                    "Durum" text NOT NULL,
                    "IzinBaslangic" timestamp with time zone,
                    "IzinBitis" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS "BakimKontrolKayitlari" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BakimPlaniId" integer NOT NULL,
                    "ParcaSablonuId" integer NOT NULL,
                    "AtananPersonelId" integer,
                    "Durum" text NOT NULL,
                    "IslemTarihi" timestamp with time zone NOT NULL,
                    "TeknisyenNotu" text NOT NULL,
                    CONSTRAINT "FK_BakimKontrolKayitlari_BakimPlani_BakimPlaniId"
                        FOREIGN KEY ("BakimPlaniId") REFERENCES "BakimPlani" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_BakimKontrolKayitlari_ParcaSablonlari_ParcaSablonuId"
                        FOREIGN KEY ("ParcaSablonuId") REFERENCES "ParcaSablonlari" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_BakimKontrolKayitlari_Personeller_AtananPersonelId"
                        FOREIGN KEY ("AtananPersonelId") REFERENCES "Personeller" ("Id") ON DELETE SET NULL
                );

                CREATE TABLE IF NOT EXISTS "PersonelHareketleri" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "PersonelId" integer NOT NULL,
                    "HareketTipi" text,
                    "Aciklama" text,
                    "Tarih" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS "Yetkinlikler" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SicilNo" text NOT NULL,
                    "ParcaPN" text,
                    "YetkinlikSeviyesi" integer NOT NULL,
                    "Aciklama" text
                );

                CREATE INDEX IF NOT EXISTS "IX_ParcaSablonlari_BakimGrubuId" ON "ParcaSablonlari" ("BakimGrubuId");
                CREATE INDEX IF NOT EXISTS "IX_BakimKontrolKayitlari_AtananPersonelId" ON "BakimKontrolKayitlari" ("AtananPersonelId");
                CREATE INDEX IF NOT EXISTS "IX_BakimKontrolKayitlari_BakimPlaniId" ON "BakimKontrolKayitlari" ("BakimPlaniId");
                CREATE INDEX IF NOT EXISTS "IX_BakimKontrolKayitlari_ParcaSablonuId" ON "BakimKontrolKayitlari" ("ParcaSablonuId");
                CREATE INDEX IF NOT EXISTS "IX_PersonelHareketleri_PersonelId" ON "PersonelHareketleri" ("PersonelId");
                """);

            // ============================================================
            // BÖLÜM 2: Normalizasyon değişiklikleri
            // ============================================================
            migrationBuilder.Sql("""
                -- Personeller: BakimGrubuId FK kolonu ekle
                ALTER TABLE "Personeller" ADD COLUMN IF NOT EXISTS "BakimGrubuId" integer;

                -- Yetkinlikler: duplike kolonları kaldır (IF EXISTS = güvenli)
                ALTER TABLE "Yetkinlikler" DROP COLUMN IF EXISTS "ParcaAdi";
                ALTER TABLE "Yetkinlikler" DROP COLUMN IF EXISTS "HelikopterTipi";
                ALTER TABLE "Yetkinlikler" DROP COLUMN IF EXISTS "AtolyeKodu";

                -- Yetkinlikler: FK kolonları ekle (DEFAULT 0 — veri migrasyonu sonrası kaldırılır)
                ALTER TABLE "Yetkinlikler" ADD COLUMN IF NOT EXISTS "PersonelId" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Yetkinlikler" ADD COLUMN IF NOT EXISTS "ParcaSablonuId" integer NOT NULL DEFAULT 0;

                -- Veri migrasyonu: SicilNo üzerinden PersonelId doldur
                UPDATE "Yetkinlikler" y
                SET "PersonelId" = p."Id"
                FROM "Personeller" p
                WHERE y."SicilNo" = p."SicilNo" AND y."PersonelId" = 0;

                -- Veri migrasyonu: ParcaPN üzerinden ParcaSablonuId doldur
                UPDATE "Yetkinlikler" y
                SET "ParcaSablonuId" = ps."Id"
                FROM "ParcaSablonlari" ps
                WHERE y."ParcaPN" = ps."ParcaPN" AND y."ParcaSablonuId" = 0;

                -- Varsayılan değerleri kaldır
                ALTER TABLE "Yetkinlikler" ALTER COLUMN "PersonelId" DROP DEFAULT;
                ALTER TABLE "Yetkinlikler" ALTER COLUMN "ParcaSablonuId" DROP DEFAULT;

                -- FK kısıtlamaları — önce varsa kaldır, sonra ekle (idempotent)
                ALTER TABLE "Personeller" DROP CONSTRAINT IF EXISTS "FK_Personeller_BakimGruplari_BakimGrubuId";
                ALTER TABLE "Personeller" ADD CONSTRAINT "FK_Personeller_BakimGruplari_BakimGrubuId"
                    FOREIGN KEY ("BakimGrubuId") REFERENCES "BakimGruplari" ("Id") ON DELETE SET NULL;

                ALTER TABLE "PersonelHareketleri" DROP CONSTRAINT IF EXISTS "FK_PersonelHareketleri_Personeller_PersonelId";
                ALTER TABLE "PersonelHareketleri" ADD CONSTRAINT "FK_PersonelHareketleri_Personeller_PersonelId"
                    FOREIGN KEY ("PersonelId") REFERENCES "Personeller" ("Id") ON DELETE CASCADE;

                ALTER TABLE "Yetkinlikler" DROP CONSTRAINT IF EXISTS "FK_Yetkinlikler_Personeller_PersonelId";
                ALTER TABLE "Yetkinlikler" ADD CONSTRAINT "FK_Yetkinlikler_Personeller_PersonelId"
                    FOREIGN KEY ("PersonelId") REFERENCES "Personeller" ("Id") ON DELETE CASCADE;

                ALTER TABLE "Yetkinlikler" DROP CONSTRAINT IF EXISTS "FK_Yetkinlikler_ParcaSablonlari_ParcaSablonuId";
                ALTER TABLE "Yetkinlikler" ADD CONSTRAINT "FK_Yetkinlikler_ParcaSablonlari_ParcaSablonuId"
                    FOREIGN KEY ("ParcaSablonuId") REFERENCES "ParcaSablonlari" ("Id") ON DELETE RESTRICT;

                -- Unique index öncesi duplikat temizliği: en yüksek Id'li kaydı tut
                DELETE FROM "Yetkinlikler" y
                USING "Yetkinlikler" y2
                WHERE y."Id" < y2."Id"
                  AND y."SicilNo" = y2."SicilNo"
                  AND y."ParcaPN" IS NOT DISTINCT FROM y2."ParcaPN";

                -- İndeksler
                CREATE INDEX IF NOT EXISTS "IX_Personeller_BakimGrubuId" ON "Personeller" ("BakimGrubuId");
                CREATE INDEX IF NOT EXISTS "IX_Yetkinlikler_PersonelId" ON "Yetkinlikler" ("PersonelId");
                CREATE INDEX IF NOT EXISTS "IX_Yetkinlikler_ParcaSablonuId" ON "Yetkinlikler" ("ParcaSablonuId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Yetkinlikler_SicilNo_ParcaPN" ON "Yetkinlikler" ("SicilNo", "ParcaPN");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "BakimKontrolKayitlari";
                DROP TABLE IF EXISTS "PersonelHareketleri";
                DROP TABLE IF EXISTS "Yetkinlikler";
                DROP TABLE IF EXISTS "BakimPlani";
                DROP TABLE IF EXISTS "ParcaSablonlari";
                DROP TABLE IF EXISTS "Personeller";
                DROP TABLE IF EXISTS "BakimGruplari";
                """);
        }
    }
}
