// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MroPlan.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MroPlan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MroPlan.Models.BakimGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtolyeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BakimGruplari");
                });

            modelBuilder.Entity("MroPlan.Models.BakimKontrolKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtananPersonelId")
                        .HasColumnType("integer");

                    b.Property<int>("BakimPlaniId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EgitimModu")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GelistirmeBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GelistirmeModu")
                        .HasColumnType("boolean");

                    b.Property<int?>("GelistirmePersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("GercekSureDk")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParcaSablonuId")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorPersonelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeknisyenNotu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtananPersonelId");

                    b.HasIndex("BakimPlaniId");

                    b.HasIndex("GelistirmePersonelId");

                    b.HasIndex("ParcaSablonuId");

                    b.HasIndex("SupervisorPersonelId");

                    b.ToTable("BakimKontrolKayitlari");
                });

            modelBuilder.Entity("MroPlan.Models.BakimPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GeldigiBirlik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenelDurum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("HedefTeslimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HeliTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KabulTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BakimPlani");
                });

            modelBuilder.Entity("MroPlan.Models.EgitimModulu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CyberColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HedefYetkinlikSeviyesi")
                        .HasColumnType("integer");

                    b.Property<string>("Ikon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParcaSablonuId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcaSablonuId");

                    b.ToTable("EgitimModulleri");
                });

            modelBuilder.Entity("MroPlan.Models.ParcaSablonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BakimGrubuId")
                        .HasColumnType("integer");

                    b.Property<int>("HazirlikSuresi")
                        .HasColumnType("integer");

                    b.Property<string>("HeliTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IslemSure")
                        .HasColumnType("integer");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParcaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParcaPN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BakimGrubuId");

                    b.ToTable("ParcaSablonlari");
                });

            modelBuilder.Entity("MroPlan.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtolyeKodu")
                        .HasColumnType("text");

                    b.Property<int?>("BakimGrubuId")
                        .HasColumnType("integer");

                    b.Property<string>("CalistigiYer")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IzinBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IzinBitis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BakimGrubuId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("MroPlan.Models.PersonelEgitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EgitimModuluId")
                        .HasColumnType("integer");

                    b.Property<int>("IlerlemeYuzdesi")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TamamlanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EgitimModuluId");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelEgitimleri");
                });

            modelBuilder.Entity("MroPlan.Models.Yetkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenSicil")
                        .HasColumnType("text");

                    b.Property<string>("ParcaPN")
                        .HasColumnType("text");

                    b.Property<int>("ParcaSablonuId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("SertifikaBelgeNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SertifikaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TamamlananKartSayisi")
                        .HasColumnType("integer");

                    b.Property<int>("YetkinlikSeviyesi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcaSablonuId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SicilNo", "ParcaPN")
                        .IsUnique();

                    b.ToTable("Yetkinlikler");
                });

            modelBuilder.Entity("MroPlan.Models.YetkinlikGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EskiSeviye")
                        .HasColumnType("integer");

                    b.Property<string>("IslemNotu")
                        .HasColumnType("text");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IslemYapanSicil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParcaPN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YeniSeviye")
                        .HasColumnType("integer");

                    b.Property<int>("YetkinlikId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YetkinlikId");

                    b.ToTable("YetkinlikGecmisi");
                });

            modelBuilder.Entity("MroPlan.Models.BakimKontrolKaydi", b =>
                {
                    b.HasOne("MroPlan.Models.Personel", "AtananPersonel")
                        .WithMany()
                        .HasForeignKey("AtananPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MroPlan.Models.BakimPlani", "BakimPlani")
                        .WithMany("KontrolKayitlari")
                        .HasForeignKey("BakimPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MroPlan.Models.Personel", "GelistirmePersonel")
                        .WithMany()
                        .HasForeignKey("GelistirmePersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MroPlan.Models.ParcaSablonu", "ParcaSablonu")
                        .WithMany()
                        .HasForeignKey("ParcaSablonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MroPlan.Models.Personel", "SupervisorPersonel")
                        .WithMany()
                        .HasForeignKey("SupervisorPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AtananPersonel");

                    b.Navigation("BakimPlani");

                    b.Navigation("GelistirmePersonel");

                    b.Navigation("ParcaSablonu");

                    b.Navigation("SupervisorPersonel");
                });

            modelBuilder.Entity("MroPlan.Models.EgitimModulu", b =>
                {
                    b.HasOne("MroPlan.Models.ParcaSablonu", "ParcaSablonu")
                        .WithMany()
                        .HasForeignKey("ParcaSablonuId");

                    b.Navigation("ParcaSablonu");
                });

            modelBuilder.Entity("MroPlan.Models.ParcaSablonu", b =>
                {
                    b.HasOne("MroPlan.Models.BakimGrubu", "BakimGrubu")
                        .WithMany()
                        .HasForeignKey("BakimGrubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimGrubu");
                });

            modelBuilder.Entity("MroPlan.Models.Personel", b =>
                {
                    b.HasOne("MroPlan.Models.BakimGrubu", "BakimGrubu")
                        .WithMany()
                        .HasForeignKey("BakimGrubuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BakimGrubu");
                });

            modelBuilder.Entity("MroPlan.Models.PersonelEgitim", b =>
                {
                    b.HasOne("MroPlan.Models.EgitimModulu", "EgitimModulu")
                        .WithMany()
                        .HasForeignKey("EgitimModuluId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MroPlan.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EgitimModulu");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("MroPlan.Models.Yetkinlik", b =>
                {
                    b.HasOne("MroPlan.Models.ParcaSablonu", "ParcaSablonu")
                        .WithMany()
                        .HasForeignKey("ParcaSablonuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MroPlan.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcaSablonu");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("MroPlan.Models.YetkinlikGecmisi", b =>
                {
                    b.HasOne("MroPlan.Models.Yetkinlik", "Yetkinlik")
                        .WithMany()
                        .HasForeignKey("YetkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yetkinlik");
                });

            modelBuilder.Entity("MroPlan.Models.BakimPlani", b =>
                {
                    b.Navigation("KontrolKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
